image: registry.gitlab.com/charts/alpine-helm

stages:
  - test
  - release

lint:
  stage: test
  script:
    - helm lint .

pages:
  stage: release
  script:
    - helm init --client-only
    - mkdir -p ./public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package . --destination ./public
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME} ./public
    - cp ./public/index.yaml ./chart_site/ && cp ../README.md ./chart_site/readme.md
    - cd chart_site && bundle install
    - jekyll build --destination ../public && rm ../public/feed.xml
  artifacts:
    paths:
      - public
  only:
    - master
